In [12]:
class Person:
  pass
print(Person)

<class '__main__.Person'>

In [15]:
ahmad=Person()
print(ahmad)

<__main__.Person object at 0x79b5a6c0d180>

In [16]:
class Student :
  def __init__(self,name):
    self.name=name
  def learn(self):
   print("welcome to oop fundamental")
student_1=Student("Sufyan")
print(student_1.name)
student_1.learn()

Sufyan
welcome to oop fundamental

In [30]:
class Student:
  def __init__(self, name, age, roll, address):
    self.name = name
    self.age = age
    self.roll = roll
    self.address = address
  def info(self):
    print("Name of student",self.name)
    print("The age of student",self.age)
    print("Roll number of student",self.roll)
    print("Address of student",self.address)


student_1 = Student("Sufyan", 18, 1, "123 Main Street")


student_1.info()

Name of student Sufyan
The age of student 18
Roll number of student 1
Address of student 123 Main Street

In [35]:
class student():
  university="air university"
  def __init__(self, name, age, roll, address,university):
    self.name = name
    self.age = age
    self.roll = roll
    self.address = address
  def info(self):
    print("Name of student is",self.name)
    print("The age of student is",self.age)
    print("Roll number of student is",self.roll)
    print("Address of student is",self.address)
    print("he is the student of",self.university)


student_1 = student("Sufyan", 18, 1, "123 Main Street","air")
student_1.info()
student_2 = student("Ali", 22, 5, "124 Main Street","air")
student_2.info()
student_1.roll=200519
Student.university="nust"
student_1.info()
student_2.info()

Name of student is Sufyan
The age of student is 18
Roll number of student is 1
Address of student is 123 Main Street
he is the student of air university
Name of student is Ali
The age of student is 22
Roll number of student is 5
Address of student is 124 Main Street
he is the student of air university
Name of student is Sufyan
The age of student is 18
Roll number of student is 200519
Address of student is 123 Main Street
he is the student of air university
Name of student is Ali
The age of student is 22
Roll number of student is 5
Address of student is 124 Main Street
he is the student of air university

In [51]:
class Student:
  def __init__(self, name, age, roll, address):
    self.name = name
    self.age = age
    self.roll = roll
    self.address = address
    self.skill=[]
  def info(self):
    print("Name of student",self.name)
    print("The age of student",self.age)
    print("Roll number of student",self.roll)
    print("Address of student",self.address)
  def add_skill(self,skill):
   self.skill.append(skill)



student_1 = Student("Sufyan", 18, 1, "123 Main Street")
student_1.add_skill('python')
student_1.add_skill('C++')
print(student_1.skill)
student_1.info()

['python', 'C++']
Name of student Sufyan
The age of student 18
Roll number of student 1
Address of student 123 Main Street

In [ ]:
class student():
  university="air university"
  def __init__(self, name, age, roll, address,university):
    self.name = name
    self.age = age
    self.roll = roll
    self.address = address
  def info(self):
    print("Name of student is",self.name)
    print("The age of student is",self.age)
    print("Roll number of student is",self.roll)
    print("Address of student is",self.address)
    print("he is the student of",self.university)


student_1 = student("Sufyan", 18, 1, "123 Main Street","air")
student_1.info()
student_2 = student("Ali", 22, 5, "124 Main Street","air")
student_2.info()
student_1.roll=200519
Student.university="nust"
student_1.info()
student_2.info()

In [61]:
class banking:
    def __init__(self, name, account_number, balance):
        self.name = name
        self.account_number = account_number
        self.balance = balance

    def info(self):
        print("Name of student",self.name)
        print("Account number of student",self.account_number)
        print("Balance of student",self.balance)

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if self.balance < amount:
            print("Insufficient balance.")
        else:
            self.balance -= amount

bank_1 = banking("Sufyan",  1234567890, 9500)
bank_1.info()

bank_2 = banking("Ali", 9876543210, 5500)
bank_2.info()
print("latest info")

bank_1.deposit(1000)
bank_1.info()


bank_2.withdraw(3000)
bank_2.info()

Name of student Sufyan
Account number of student 1234567890
Balance of student 9500
Name of student Ali
Account number of student 9876543210
Balance of student 5500
latest info
Name of student Sufyan
Account number of student 1234567890
Balance of student 10500
Name of student Ali
Account number of student 9876543210
Balance of student 2500