In [2]:
class Animal:
    def __init__(self, name, species):
        self.name = name
        self.species = species

    def display_info(self):
        print(f"Name: {self.name}, Species: {self.species}")

class Dog(Animal):
    def __init__(self, name, breed):
        super().__init__(name, species="Dog")
        self.breed = breed

    def display_info(self):
        print(f"Name: {self.name}, Species: {self.species}, Breed: {self.breed}")

dog = Dog("Buddy", "Golden Retriever")

dog.display_info()

Name: Buddy, Species: Dog, Breed: Golden Retriever

In [3]:
class Car:
    def __init__(self, make, model, year, price):
        self.make = make
        self.model = model
        self.year = year
        self.price = price

    def display_info(self):
        print(f"Make: {self.make}, Model: {self.model}, Year: {self.year}, Price: {self.price}")

car = Car("Toyota", "Corolla", 2023, 25000)

car.display_info()

Make: Toyota, Model: Corolla, Year: 2023, Price: 25000